# Generated by Django 4.0.5 on 2022-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_employeecontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
